### ISSUE TITLE
How about a bookmarklet

### ISSUE THREAD

**Issue by jasonadelia** [chrisnager/simple-debug.css#1]
`<a href="javascript:(function (){newcss = '*{outline:1px solid #fff!important;background-color:rgba(0,2,54,.1)!important}';if ('\v'=='v') /* ie only */ {document.createStyleSheet().cssText = newcss;} else {var tag = document.createElement('style'); tag.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(tag);tag[ (typeof document.body.style.WebkitAppearance=='string') /* webkit only */ ? 'innerText' : 'innerHTML'] = newcss;}})();">bookmarklet</a>`

altered from: http://www.paulirish.com/2008/bookmarklet-inject-new-css-rules/

**Comment by chrisnager** [comment]
That's a great idea. I wanted to make a bookmarklet or browser extension for simple-debug.css. Thanks for putting this together!
